// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: api/eta-service.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNearestCarEtaV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *GetNearestCarEtaV1Request) Reset() {
	*x = GetNearestCarEtaV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eta_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNearestCarEtaV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearestCarEtaV1Request) ProtoMessage() {}

func (x *GetNearestCarEtaV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_eta_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearestCarEtaV1Request.ProtoReflect.Descriptor instead.
func (*GetNearestCarEtaV1Request) Descriptor() ([]byte, []int) {
	return file_api_eta_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetNearestCarEtaV1Request) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetNearestCarEtaV1Request) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GetNearestCarEtaV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *GetNearestCarEtaV1Response_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetNearestCarEtaV1Response) Reset() {
	*x = GetNearestCarEtaV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eta_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNearestCarEtaV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearestCarEtaV1Response) ProtoMessage() {}

func (x *GetNearestCarEtaV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_eta_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearestCarEtaV1Response.ProtoReflect.Descriptor instead.
func (*GetNearestCarEtaV1Response) Descriptor() ([]byte, []int) {
	return file_api_eta_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetNearestCarEtaV1Response) GetData() *GetNearestCarEtaV1Response_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetNearestCarEtaV1Response_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarId int64 `protobuf:"varint,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	Eta   int64 `protobuf:"varint,2,opt,name=eta,proto3" json:"eta,omitempty"`
}

func (x *GetNearestCarEtaV1Response_Data) Reset() {
	*x = GetNearestCarEtaV1Response_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_eta_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNearestCarEtaV1Response_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearestCarEtaV1Response_Data) ProtoMessage() {}

func (x *GetNearestCarEtaV1Response_Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_eta_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearestCarEtaV1Response_Data.ProtoReflect.Descriptor instead.
func (*GetNearestCarEtaV1Response_Data) Descriptor() ([]byte, []int) {
	return file_api_eta_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetNearestCarEtaV1Response_Data) GetCarId() int64 {
	if x != nil {
		return x.CarId
	}
	return 0
}

func (x *GetNearestCarEtaV1Response_Data) GetEta() int64 {
	if x != nil {
		return x.Eta
	}
	return 0
}

var File_api_eta_service_proto protoreflect.FileDescriptor

var file_api_eta_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x74, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x55, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74,
	0x43, 0x61, 0x72, 0x45, 0x74, 0x61, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x4e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x43, 0x61, 0x72, 0x45, 0x74, 0x61, 0x56, 0x31,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x43,
	0x61, 0x72, 0x45, 0x74, 0x61, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x2f, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x63, 0x61, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x74, 0x61, 0x32, 0xb4, 0x01, 0x0a, 0x0a,
	0x45, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0xa5, 0x01, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x43, 0x61, 0x72, 0x45, 0x74, 0x61, 0x56,
	0x31, 0x12, 0x26, 0x2e, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x43, 0x61, 0x72, 0x45, 0x74, 0x61,
	0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x65, 0x74, 0x61, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x65,
	0x73, 0x74, 0x43, 0x61, 0x72, 0x45, 0x74, 0x61, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x3e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x38, 0x12, 0x36, 0x2f, 0x76, 0x31, 0x2f,
	0x67, 0x65, 0x74, 0x2d, 0x6e, 0x65, 0x61, 0x72, 0x65, 0x73, 0x74, 0x2d, 0x63, 0x61, 0x72, 0x2d,
	0x65, 0x74, 0x61, 0x2f, 0x6c, 0x61, 0x74, 0x2f, 0x7b, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x7d, 0x2f, 0x6c, 0x6e, 0x67, 0x2f, 0x7b, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x7d, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_eta_service_proto_rawDescOnce sync.Once
	file_api_eta_service_proto_rawDescData = file_api_eta_service_proto_rawDesc
)

func file_api_eta_service_proto_rawDescGZIP() []byte {
	file_api_eta_service_proto_rawDescOnce.Do(func() {
		file_api_eta_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_eta_service_proto_rawDescData)
	})
	return file_api_eta_service_proto_rawDescData
}

var file_api_eta_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_eta_service_proto_goTypes = []interface{}{
	(*GetNearestCarEtaV1Request)(nil),       // 0: eta_service.GetNearestCarEtaV1Request
	(*GetNearestCarEtaV1Response)(nil),      // 1: eta_service.GetNearestCarEtaV1Response
	(*GetNearestCarEtaV1Response_Data)(nil), // 2: eta_service.GetNearestCarEtaV1Response.Data
}
var file_api_eta_service_proto_depIdxs = []int32{
	2, // 0: eta_service.GetNearestCarEtaV1Response.data:type_name -> eta_service.GetNearestCarEtaV1Response.Data
	0, // 1: eta_service.EtaService.GetNearestCarEtaV1:input_type -> eta_service.GetNearestCarEtaV1Request
	1, // 2: eta_service.EtaService.GetNearestCarEtaV1:output_type -> eta_service.GetNearestCarEtaV1Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_eta_service_proto_init() }
func file_api_eta_service_proto_init() {
	if File_api_eta_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_eta_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNearestCarEtaV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_eta_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNearestCarEtaV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_eta_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNearestCarEtaV1Response_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_eta_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_eta_service_proto_goTypes,
		DependencyIndexes: file_api_eta_service_proto_depIdxs,
		MessageInfos:      file_api_eta_service_proto_msgTypes,
	}.Build()
	File_api_eta_service_proto = out.File
	file_api_eta_service_proto_rawDesc = nil
	file_api_eta_service_proto_goTypes = nil
	file_api_eta_service_proto_depIdxs = nil
}
