// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: api/eta-service.proto

/*
Package api is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package api

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_EtaService_GetNearestCarEtaV1_0(ctx context.Context, marshaler runtime.Marshaler, client EtaServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetNearestCarEtaV1Request
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["latitude"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "latitude")
	}

	protoReq.Latitude, err = runtime.Float64(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "latitude", err)
	}

	val, ok = pathParams["longitude"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "longitude")
	}

	protoReq.Longitude, err = runtime.Float64(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "longitude", err)
	}

	msg, err := client.GetNearestCarEtaV1(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_EtaService_GetNearestCarEtaV1_0(ctx context.Context, marshaler runtime.Marshaler, server EtaServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetNearestCarEtaV1Request
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["latitude"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "latitude")
	}

	protoReq.Latitude, err = runtime.Float64(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "latitude", err)
	}

	val, ok = pathParams["longitude"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "longitude")
	}

	protoReq.Longitude, err = runtime.Float64(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "longitude", err)
	}

	msg, err := server.GetNearestCarEtaV1(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterEtaServiceHandlerServer registers the http handlers for service EtaService to "mux".
// UnaryRPC     :call EtaServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterEtaServiceHandlerFromEndpoint instead.
func RegisterEtaServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server EtaServiceServer) error {

	mux.Handle("GET", pattern_EtaService_GetNearestCarEtaV1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/eta_service.EtaService/GetNearestCarEtaV1")
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_EtaService_GetNearestCarEtaV1_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_EtaService_GetNearestCarEtaV1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterEtaServiceHandlerFromEndpoint is same as RegisterEtaServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterEtaServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterEtaServiceHandler(ctx, mux, conn)
}

// RegisterEtaServiceHandler registers the http handlers for service EtaService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterEtaServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterEtaServiceHandlerClient(ctx, mux, NewEtaServiceClient(conn))
}

// RegisterEtaServiceHandlerClient registers the http handlers for service EtaService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "EtaServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "EtaServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "EtaServiceClient" to call the correct interceptors.
func RegisterEtaServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client EtaServiceClient) error {

	mux.Handle("GET", pattern_EtaService_GetNearestCarEtaV1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/eta_service.EtaService/GetNearestCarEtaV1")
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_EtaService_GetNearestCarEtaV1_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_EtaService_GetNearestCarEtaV1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_EtaService_GetNearestCarEtaV1_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3, 2, 4, 1, 0, 4, 1, 5, 5}, []string{"v1", "get-nearest-car-eta", "lat", "latitude", "lng", "longitude"}, ""))
)

var (
	forward_EtaService_GetNearestCarEtaV1_0 = runtime.ForwardResponseMessage
)
