// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/erizaver/eta-service/internal/pkg/model"
)

// CarsFacade is an autogenerated mock type for the CarsFacade type
type CarsFacade struct {
	mock.Mock
}

// GetNearestCars provides a mock function with given fields: ctx, lat, lng
func (_m *CarsFacade) GetNearestCars(ctx context.Context, lat float64, lng float64) ([]model.Car, error) {
	ret := _m.Called(ctx, lat, lng)

	var r0 []model.Car
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) []model.Car); ok {
		r0 = rf(ctx, lat, lng)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Car)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lat, lng)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
