// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "github.com/erizaver/eta-service/internal/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// RedisFacade is an autogenerated mock type for the RedisFacade type
type RedisFacade struct {
	mock.Mock
}

// AddEtaToCache provides a mock function with given fields: car, lat, lng
func (_m *RedisFacade) AddEtaToCache(car model.NearestCar, lat float64, lng float64) error {
	ret := _m.Called(car, lat, lng)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.NearestCar, float64, float64) error); ok {
		r0 = rf(car, lat, lng)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEtaFromCache provides a mock function with given fields: lat, lng
func (_m *RedisFacade) GetEtaFromCache(lat float64, lng float64) (model.NearestCar, error) {
	ret := _m.Called(lat, lng)

	var r0 model.NearestCar
	if rf, ok := ret.Get(0).(func(float64, float64) model.NearestCar); ok {
		r0 = rf(lat, lng)
	} else {
		r0 = ret.Get(0).(model.NearestCar)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(float64, float64) error); ok {
		r1 = rf(lat, lng)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
