// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPredictParams creates a new PredictParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPredictParams() *PredictParams {
	return &PredictParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPredictParamsWithTimeout creates a new PredictParams object
// with the ability to set a timeout on a request.
func NewPredictParamsWithTimeout(timeout time.Duration) *PredictParams {
	return &PredictParams{
		timeout: timeout,
	}
}

// NewPredictParamsWithContext creates a new PredictParams object
// with the ability to set a context for a request.
func NewPredictParamsWithContext(ctx context.Context) *PredictParams {
	return &PredictParams{
		Context: ctx,
	}
}

// NewPredictParamsWithHTTPClient creates a new PredictParams object
// with the ability to set a custom HTTPClient for a request.
func NewPredictParamsWithHTTPClient(client *http.Client) *PredictParams {
	return &PredictParams{
		HTTPClient: client,
	}
}

/* PredictParams contains all the parameters to send to the API endpoint
   for the predict operation.

   Typically these are written to a http.Request.
*/
type PredictParams struct {

	// PositionList.
	PositionList PredictBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the predict params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PredictParams) WithDefaults() *PredictParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the predict params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PredictParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the predict params
func (o *PredictParams) WithTimeout(timeout time.Duration) *PredictParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the predict params
func (o *PredictParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the predict params
func (o *PredictParams) WithContext(ctx context.Context) *PredictParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the predict params
func (o *PredictParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the predict params
func (o *PredictParams) WithHTTPClient(client *http.Client) *PredictParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the predict params
func (o *PredictParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPositionList adds the positionList to the predict params
func (o *PredictParams) WithPositionList(positionList PredictBody) *PredictParams {
	o.SetPositionList(positionList)
	return o
}

// SetPositionList adds the positionList to the predict params
func (o *PredictParams) SetPositionList(positionList PredictBody) {
	o.PositionList = positionList
}

// WriteToRequest writes these params to a swagger request
func (o *PredictParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.PositionList); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
